courses/urls.py
from django.urls import path, re_path

from . import views

app_name = "courses"
urlpatterns = [
    path("", views.CourseListView.as_view(), name="list"),
    path("<int:pk>/", views.CourseDetailView.as_view(), name="detail"),
    path("<int:course_pk>/t<int:step_pk>/", views.TextDetailView.as_view(), name="text"),
    path("<int:course_pk>/q<int:step_pk>/", views.QuizDetailView.as_view(), name="quiz"),
    path("<int:course_pk>/create_quiz/", views.QuizCreateView.as_view(), name="create_quiz"),
    path("<int:course_pk>/edit_quiz/<int:quiz_pk>/", views.QuizEditView.as_view(), name="edit_quiz"),
    path("<int:course_pk>/edit_text/<int:text_pk>/", views.TextEditView.as_view(), name="edit_text"),
    re_path(r"(?P<quiz_pk>\d+)/create_question/(?P<question_type>mc|tf)/$",
            views.QuestionCreateView.as_view(), name="create_question"),

    # not neat but to show we can use url patterns to direct views
    path("<int:quiz_pk>/edit_mc_question/<int:question_pk>/",
         views.MCQuestionEditView.as_view(), name="edit_mc_question"),
    path("<int:quiz_pk>/edit_tf_question/<int:question_pk>/",
         views.TFQuestionEditView.as_view(), name="edit_tf_question"),

    path("<int:question_pk>/edit_answer/", views.AnswerEditView.as_view(), name="edit_answer"),
    path("question/<int:question_pk>/", views.AnswerListView.as_view(), name="list_answer"),
]

learners_cafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import HelloView, HomeView, SuggestionFormView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("hello/", HelloView.as_view(), name="hello"),
    path("", HomeView.as_view(), name="home"),
    path("suggestion/", SuggestionFormView.as_view(), name="suggestion"),
    path("courses/", include("courses.urls")),
]


urlpatterns += staticfiles_urlpatterns()

courses/models.py
from django.db import models
from django.urls import reverse


class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title


class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        abstract = True
        ordering = ["order"]


class Text(Step):

    content = models.TextField(blank=True, default="")

    def get_absolute_url(self):
        return reverse("courses:text", kwargs={
            "course_pk": self.course_id,
            "step_pk": self.id,
        })


class Quiz(Step):

    total_questions = models.IntegerField(default=4)

    class Meta:
        verbose_name_plural = "Quizzes"

    def get_absolute_url(self):
        return reverse("courses:quiz", kwargs={
            "course_pk": self.course_id,
            "step_pk": self.id,
        })


class Question(models.Model):

    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    order = models.IntegerField(default=0)
    prompt = models.TextField()

    class Meta:
        ordering = ['order']

    def get_absolute_url(self):
        return self.quiz.get_absolute_url()

    def __str__(self):
        return self.prompt


class MultipleChoiceQuestion(Question):
    shuffle_answers = models.BooleanField(default=False)


class TrueFalseQuestion(Question):
    pass


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    order = models.IntegerField(default=0)
    text = models.CharField(max_length=255)
    correct = models.BooleanField(default=False)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.text

courses/forms.py
from django import forms

from . import models


class QuizForm(forms.ModelForm):
    class Meta:
        model = models.Quiz
        fields = [
            "title",
            "description",
            "order",
            "total_questions",
        ]


class TrueFalseQuestionForm(forms.ModelForm):
    class Meta:
        model = models.TrueFalseQuestion
        fields = ["order", "prompt"]


class MultipleChoiceQuestionForm(forms.ModelForm):
    class Meta:
        model = models.MultipleChoiceQuestion
        fields = [
            "order",
            "prompt",
            "shuffle_answers",
        ]


class AnswerForm(forms.ModelForm):

    class Meta:
        model = models.Answer
        fields = [
            "order",
            "text",
            "correct",
        ]

courses/views.py
from itertools import chain

from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, FormView,
)
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import modelformset_factory

from . import models
from . import forms


class CourseListView(ListView):
    model = models.Course


class CourseDetailView(DetailView):
    model = models.Course
    template_name = "courses/course_detail.html"

    def get_context_data(self, **kwargs):
        # course = super().get_queryset()
        course = get_object_or_404(models.Course, id=self.kwargs["pk"])
        context = super().get_context_data(**kwargs)
        steps = sorted(
            chain(course.text_set.all(), course.quiz_set.all()),
            key=lambda step: step.order
        )
        context["steps"] = steps
        context["course"] = course
        return context


# from django.shortcuts import render, get_object_or_404
#
#
# def step_detail(request, **kwargs):
#     course_pk = kwargs["course_pk"]
#     step_pk = kwargs["step_pk"]
#     step = get_object_or_404(Step, course=course_pk, pk=step_pk)
#     return render(request, "courses/step_detail.html", {"step": step})


class TextDetailView(DetailView):

    model = models.Text
    query_pk_and_slug = True
    slug_field = "course"
    slug_url_kwarg = "course_pk"
    pk_url_kwarg = "step_pk"
    template_name = "courses/text_detail.html"


class QuizDetailView(DetailView):

    model = models.Quiz
    query_pk_and_slug = True
    slug_field = "course"
    slug_url_kwarg = "course_pk"
    pk_url_kwarg = "step_pk"
    template_name = "courses/quiz_detail.html"
    # # once you define context_object_name "quiz", quiz_detail.html matches the default
    # # template name, so you don't need it anymore.
    # template_name = "courses/quiz_detail.html"


class QuizCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = "course"
    pk_url_kwarg = "course_pk"
    context_object_name = 'course'
    form_class = forms.QuizForm
    template_name = "courses/quiz_create.html"
    success_message = "%(title)s was created successfully"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course_pk = self.kwargs.get(self.pk_url_kwarg)
        course = get_object_or_404(models.Course, pk=course_pk)
        context["course"] = course
        return context

    def form_valid(self, form):
        course_pk = self.kwargs.get(self.pk_url_kwarg)
        form.instance.course = get_object_or_404(models.Course, pk=course_pk)
        return super().form_valid(form)

    def get_success_url(self):
        course_pk = self.kwargs["course_pk"]
        return reverse_lazy('courses:detail', kwargs={'pk': course_pk})
        # More: how to get the quiz id from the above quiz form


class QuizEditView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    query_pk_and_slug = True
    slug_field = "course"
    slug_url_kwarg = "course_pk"
    pk_url_kwarg = "quiz_pk"
    model = models.Quiz
    form_class = forms.QuizForm
    success_message = "%(title)s was updated successfully"
    template_name = "courses/quiz_edit.html"


class TextEditView(LoginRequiredMixin, UpdateView):
    """To be added"""


class QuestionCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    deal with both multiple choice question and true/false questions,
    from re_path patterns in one view.
    """
    pk_url_kwarg = "quiz_pk"
    success_message = "%(prompt)s was created successfully"
    template_name = "courses/question_create.html"

    def get_form_class(self):
        if self.kwargs.get("question_type") == "mc":
            self.form_class = forms.MultipleChoiceQuestionForm
        elif self.kwargs.get("question_type") == "tf":
            self.form_class = forms.TrueFalseQuestionForm
        return self.form_class

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        quiz_pk = self.kwargs.get(self.pk_url_kwarg)
        quiz = get_object_or_404(models.Quiz, pk=quiz_pk)
        context["quiz"] = quiz
        return context

    def form_valid(self, form):
        quiz_pk = self.kwargs.get(self.pk_url_kwarg)
        form.instance.quiz = get_object_or_404(models.Quiz, pk=quiz_pk)
        return super().form_valid(form)


class QuestionEditView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    query_pk_and_slug = True
    slug_field = "quiz"
    slug_url_kwarg = "quiz_pk"
    pk_url_kwarg = "question_pk"
    success_message = "%(prompt)s was updated successfully"
    template_name = "courses/question_edit.html"


class MCQuestionEditView(QuestionEditView):
    model = models.MultipleChoiceQuestion
    form_class = forms.MultipleChoiceQuestionForm


class TFQuestionEditView(QuestionEditView):
    model = models.TrueFalseQuestion
    form_class = forms.TrueFalseQuestionForm


class AnswerEditView(FormView):
    form_class = modelformset_factory(
        models.Answer,
        fields=["order", "text", "correct"],
        extra=3,
    )
    template_name = "courses/answer_edit.html"

    def get_form_kwargs(self):
        question_pk = self.kwargs.get("question_pk")
        kwargs = super().get_form_kwargs()
        if models.Answer.objects.filter(pk=question_pk):
            kwargs["queryset"] = models.Answer.objects.filter(question=question_pk)
        else:
            kwargs["queryset"] = models.Answer.objects.none()
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question_pk = self.kwargs.get("question_pk")
        if "question" not in kwargs:
            context["question"] = get_object_or_404(models.Question, pk=question_pk)
        return context

    def form_valid(self, formset):
        question_pk = self.kwargs.get("question_pk")
        for form in formset:
            if form.has_changed():
                print("Question PK", question_pk)
                form.instance.question = get_object_or_404(models.Question, pk=question_pk)
                print("Form", form)
                form.save()
        return super().form_valid(form=formset)

    def get_success_url(self):
        question_pk = self.kwargs.get("question_pk")
        return reverse_lazy("courses:list_answer", kwargs={'question_pk': question_pk})


class AnswerListView(ListView):

    template_name = "courses/answer_list.html"

    def get_queryset(self):
        question_pk = self.kwargs.get("question_pk")
        queryset = models.Answer.objects.filter(question=question_pk)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question_pk = self.kwargs.get("question_pk")
        if "question" not in kwargs:
            context["question"] = get_object_or_404(models.Question, pk=question_pk)
        return context

courses/templates/courses/answer_edit.html
{% extends "courses/layout.html" %}


{% block title %}Answer Form{% endblock %}

{% block content %}
    <h4>{{ question.prompt }}</h4>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="waves-effect waves-light btn" value="Save">
    </form>

{% endblock content %}

courses/templates/courses/answer_list.html
{% extends "courses/layout.html" %}


{% block title %}Answers{% endblock %}

{% block content %}

  <ul class="collection with-header">
    <li class="collection-header"><h4>{{ question.prompt }}</h4></li>
    {% for answer in object_list %}
      <li class="collection-item">{{ answer }}</li>
    {% empty %}
      <li>No answer available yet!</li>
    {% endfor %}
  </ul>

{% endblock content %}

courses/templates/courses/course_detail.html
{% extends "layout.html" %}

{% block title %}
    Courses Details
{% endblock %}

{% block content %}
    <ul class="collection with-header">

    <li class="collection-header"><h4>{{ course.title }}</h4>
        {{ course.description }}
    </li>

    {% for step in steps %}
        <li class="collection-item">
        <h5><a href="{{ step.get_absolute_url }}">{{ step.title|title }}</a></h5>
        {{ step.description }}
        </li>
    {% endfor %}


    </ul>

    {% if user.is_authenticated %}
        <hr>
        <a href="{% url 'courses:create_quiz' course_pk=course.id %}"
        class="waves-effect waves-light btn">
        <i class="material-icons left">add</i>
        new quiz</a>

        <a href="#"
        class="waves-effect waves-light disabled btn">
        <i class="material-icons left">add</i>
        new text</a>
    {% endif %}

{% endblock content %}

courses/templates/courses/course_list.html
{% extends "layout.html" %}

{% block title %}
    Available Courses
{% endblock %}

{% block content %}
    <div class="collection">
    {% for course in object_list %}
        <a class="collection-item" href="{% url "courses:detail" pk=course.pk %}">{{ course.title }}</a>
    {% endfor %}
    </div>
{% endblock %}

courses/templates/courses/layout.html
{% extends "layout.html" %}

{% block title %}Courses | {{ block.super }}{% endblock %}

{% block content %}
    {{ block.super }}

{% endblock content %}

courses/templates/courses/question_create.html
{% extends "courses/layout.html" %}

{% block title %}
    New question for {{ quiz.title  }}
{% endblock %}

{% block content %}
    <h1>{{ quiz.title }}</h1>
    <h2>Make a new question</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="waves-effect waves-light btn" value="Save">
    </form>

{% endblock content %}

courses/templates/courses/question_edit.html
{% extends "courses/layout.html" %}

{% block title %}{{ form.instance.quiz }}{% endblock %}

{% block content %}
    <h1><a href="{%  url 'courses:detail' object.quiz.course.id %}">

        {{ form.instance.quiz.course }}</a>
    </h1>
    <h2><a href="{{ object.quiz.get_absolute_url }}">
        {{ form.instance.quiz }}</a>
    </h2>
    <form method="post" action="">
        {% csrf_token %}

        <p>
            {{ form.order.errors }}
            {{ form.order.label_tag }}
            {{ form.order }}
        </p>

        <p>
            {{ form.prompt.errors }}
            {{ form.prompt.label_tag }}
            {{ form.prompt }}
        </p>

        <!-- to make Material CSS happy -->
        <p>
            {{ form.suffle_answers.errors }}

            <label for="id_shuffle_answers">
            <input type="checkbox"  name="{{ form.shuffle_answers.name }}" id="id_shuffle_answers"
            {% if form.shuffle_answers.value %}checked{% endif %}/>
            <span>{{ form.shuffle_answers.label }}</span>
            </label>
        </p>

        <input type="submit" class="waves-effect waves-light btn" value="Save">
    </form>

{% endblock content %}

courses/templates/courses/question_form.html
{% extends "courses/layout.html" %}

{% block title %}
    New question for {{ quiz.title  }}
{% endblock %}

{% block content %}
    <h1>{{ quiz.title }}</h1>
    <h2>Make a new question</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="waves-effect waves-light btn" value="Save">
    </form>

{% endblock content %}

courses/templates/courses/quiz_create.html
{% extends "courses/layout.html" %}

{% block title %}New Quiz | {{ course.title }} | {{ block.super }}{% endblock %}

{% block content %}

    <h3><a href="{% url 'courses:detail' pk=course.id %}">{{ course.title }}</a></h3>
    <h4>Make a new quiz</h4>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="action">Add</button>
    </form>

{% endblock content %}

courses/templates/courses/quiz_detail.html
{% extends "courses/step_detail.html" %}

{% block title %}Quiz Details{% endblock %}

{% block question %}
    <ul>
    {% for question in object.question_set.all %}
        <li>
        {% if question.multiplechoicequestion %}
            <a href="{% url 'courses:list_answer' question_pk=question.pk %}">
                {{ question }}
            </a>
        {% elif question.truefalsequestion %}
            <a href="{% url 'courses:list_answer' question_pk=question.pk %}">
                {{ question }}
            </a>
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'courses:edit_answer' question_pk=question.pk %}"
            class="waves-effect waves-light btn-small lighten-5">
            <i class="material-icons">edit</i></a>
        {% endif %}
        </li>
    {% endfor %}
    </ul>
{% endblock question %}

{% block step %}
{% if user.is_authenticated %}
    <a href="{% url 'courses:create_question' quiz_pk=object.pk question_type='mc' %}"
        class="waves-effect waves-light btn">
        <i class="material-icons left">question_answer</i>New Multiple Choice Question</a>
    <a href="{% url 'courses:create_question' quiz_pk=object.pk question_type='tf' %}"
        class="waves-effect waves-light btn">
        <i class="material-icons left">thumbs_up_down</i>New True/False Question</a>
{% endif %}
{% endblock step %}

courses/templates/courses/quiz_edit.html
{% extends "courses/layout.html" %}

{% block title %}{{ form.instance.title|default:"New Quiz" }} | {{ course.title }} | {{ block.super }}{% endblock %}

{% block content %}

    <h3><a href="{% url 'courses:detail' pk=object.course.id %}">{{ object.course.title }}</a></h3>
    <h4>{{ form.instance.title|default:"Make a new quiz" }} </h4>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn waves-effect waves-light" type="submit" name="action">Save
            <i class="material-icons right">save</i>
        </button>
    </form>

{% endblock content %}

courses/templates/courses/quiz_form.html
{% extends "courses/layout.html" %}

{% block title %}New Quiz | {{ course.title }} | {{ block.super }}{% endblock %}

{% block breadcrumb %}
    <a href="{% url 'courses:detail' pk=course.id %}" class="breadcrumb">{{ course.title }}</a>
{% endblock breadcrumb %}

{% block content %}
    <h1>Make a new quiz</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn waves-effect waves-light" type="submit" name="action">Save
            <i class="material-icons right">save</i>
        </button>
    </form>
{% endblock content %}

courses/templates/courses/step_detail.html
{% extends "layout.html" %}

{% block title %}Course | {{ block.super }}{% endblock %}

{% block content %}
    <h2><a href="{% url "courses:detail" pk=object.course_id %}">{{ object.course.title }}</a></h2>
    <h3>{{ object.title }}</h3>
    {{ object.description|linebreaks }}
        {{ object.content|linebreaks }}

    {% block question %}{% endblock %}

    <hr>

    {% block step %}{% endblock %}

{% endblock %}

courses/templates/courses/text_detail.html
{% extends "courses/step_detail.html" %}

{% block title %}Text Details{% endblock %}

{% block step %}
    <a href="{% url 'courses:edit_text' course_pk=object.course_id text_pk=object.id %}"
        class="waves-effect waves-light btn">
        <i class="material-icons left">edit</i>Edit</a>
{% endblock %}