courses/urls.py
from django.urls import path, re_path

from . import views

app_name = "courses"
urlpatterns = [
    path("", views.CourseListView.as_view(), name="list"),
    path("<int:pk>/", views.CourseDetailView.as_view(), name="detail"),
    path("<int:course_pk>/t<int:step_pk>/", views.TextDetailView.as_view(), name="text"),
    path("<int:course_pk>/q<int:step_pk>/", views.QuizDetailView.as_view(), name="quiz"),
    path("<int:course_pk>/create_quiz/", views.QuizCreateView.as_view(), name="create_quiz"),
    path("<int:course_pk>/edit_quiz/<int:quiz_pk>/", views.QuizEditView.as_view(), name="edit_quiz"),
    path("<int:course_pk>/edit_text/<int:text_pk>/", views.TextEditView.as_view(), name="edit_text"),
    re_path(r"(?P<quiz_pk>\d+)/create_question/(?P<question_type>mc|tf)/$",
            views.QuestionCreateView.as_view(), name="create_question"),

    # not neat but to show we can use url patterns to direct views
    path("<int:quiz_pk>/edit_mc_question/<int:question_pk>/",
         views.MCQuestionEditView.as_view(), name="edit_mc_question"),
    path("<int:quiz_pk>/edit_tf_question/<int:question_pk>/",
         views.TFQuestionEditView.as_view(), name="edit_tf_question"),

    path("<int:question_pk>/edit_answer/", views.AnswerEditView.as_view(), name="edit_answer"),
    path("question/<int:question_pk>/", views.AnswerListView.as_view(), name="list_answer"),
]

learners_cafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import HelloView, HomeView, SuggestionFormView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("hello/", HelloView.as_view(), name="hello"),
    path("", HomeView.as_view(), name="home"),
    path("suggestion/", SuggestionFormView.as_view(), name="suggestion"),
    path("courses/", include("courses.urls")),
]


urlpatterns += staticfiles_urlpatterns()

templates/home.html
{% extends "layout.html" %}

{% block content %}
<h1>Welcome to Learner's Cafe!</h1>
{% endblock %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}" media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/layout.css' %}" media="screen,projection"/>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

</head>
<body>
<div class="container">
    <nav>
        <div class="nav-wrapper">
            <div class="col s12">
                <a href="{% url 'home' %}" class="breadcrumb">Home</a>
                <a href="{% url 'courses:list' %}" class="breadcrumb">Course</a>
                {% block breadcrumb %}{% endblock %}
            </div>
        </div>
    </nav>

    <div>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div>
    {% block content %}{% endblock %}
    </div>

    <!--JavaScript at end of body for optimized loading-->
    <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
</div>
</body>
</html>

templates/suggestion_form.html
{% extends "layout.html" %}

{% block title %}New Ideas{% endblock %}

{% block content %}
<h1>We want to hear your suggestions!</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send" />
</form>
{% endblock %}